stages:
 - build
 - test
 - deploy

build:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  script:
    - apk add bash curl git make
    - make pull
    - make prod
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - make push-commit

test:
  image: docker:stable
  stage: test
  services:
    - docker:dind
  script:
    - apk add bash curl git make
    - make pull
    - make start-prod
    - sleep 5 && make dls
    - make test || bash ops/logs.sh proxy

deploy:
  image: docker:stable
  stage: deploy
  services:
    - docker:dind
  only:
    refs:
      - master
  script:
    - apk add bash curl git make
    - make pull
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - make push-release
    - >
      docker build --tag ssh-action ops/ssh-action/ && docker run ssh-action $BLOG_SERVER $SSH_KEY <<<EOF
        set -e
        echo "Successfully connected to `hostname`"
        exit
      EOF
