stages:
 - build
 - test
 - deploy

build:
  image: docker:latest
  stage: build
  script:
    - apk add make
    - make prod

test:
  image: docker:latest
  stage: test
  script:
    - apk add make
    - make pull
    - make start-prod

deploy:
  image: docker:latest
  stage: deploy
  only:
    refs:
      - master
  script:
    - apk add openssh
    - echo "Attempting to deploy"
    - >
      ssh -o StrictHostKeyChecking=no $BLOG_SERVER <<<EOF
        set -e
        echo "Successfully connected to `hostname`"
        exit
      EOF
