stages:
 - build
 - test
 - deploy

build:
  image: docker:stable
  stage: build
  services:
    - name: docker:dind
      alias: localhost
  script:
    - apk add bash curl git jq make
    - make pull-latest
    - make all
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - make push

test:
  image: docker:stable
  stage: test
  services:
    - name: docker:dind
      alias: localhost
  variables:
    BLOG_DOMAINNAME: "localhost"
    BLOG_PROD: "true"
  script:
    - apk add bash curl git jq make
    - make pull-commit
    - BLOG_DOMAINNAME="" BLOG_PROD="true" make restart
    - sleep 5
    - make dls
    - docker service logs --raw --tail 100 blog_server
    - docker service logs --raw --tail 100 blog_webserver
    - docker service logs --raw --tail 100 blog_proxy
    - make test

deploy:
  image: docker:stable
  stage: deploy
  services:
    - name: docker:dind
      alias: localhost
  only:
    refs:
      - prod
  script:
    - apk add bash curl git jq make
    - make pull-commit
    - make push $(grep -m 1 '"version":' package.json | cut -d '"' -f 4)
    - >
      docker build --tag ssh-action ops/ssh-action;
      docker run \
        --env=CI_COMMIT_SHA=$CI_COMMIT_SHA \
        --env=CI_PROJECT_NAME=$CI_PROJECT_NAME \
        --env=CI_REPOSITORY_URL=$CI_REPOSITORY_URL \
        ssh-action $SERVER_URL $SSH_KEY '
          git checkout --force prod;
          git reset --hard $CI_COMMIT_SHA;
          export BLOG_PROD="true";
          make pull-commit;
          make restart;
          docker container prune -f;
          docker image ls -q | xargs docker image rm 2> /dev/null || true;
        '
