stages:
 - build
 - test
 - deploy

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - apk add bash curl git make
    - make pull
    - make prod
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - make push-commit

test:
  image: docker:latest
  stage: test
  services:
    - docker:dind
  script:
    - apk add bash curl git make
    - make pull
    - make start-prod

deploy:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  only:
    refs:
      - master
  script:
    - apk add bash curl git make
    - make pull
    - make push-release
    - >
      ssh -o StrictHostKeyChecking=no $BLOG_SERVER <<<EOF
        set -e
        echo "Successfully connected to `hostname`"
        exit
      EOF
