stages:
 - build
 - test
 - deploy

build:
  image: docker:stable
  stage: build
  services:
    - name: docker:dind
      alias: localhost
  script:
    - apk add bash curl git make
    - make pull
    - make prod
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - make push-commit

test:
  image: docker:stable
  stage: test
  services:
    - name: docker:dind
      alias: localhost
  script:
    - apk add bash curl git make
    - make pull
    - BLOG_DOMAINNAME=localhost make start-prod
    - sleep 15
    - make dls
    - docker service logs --raw --tail 100 blog_server
    - docker service logs --raw --tail 100 blog_proxy
    - make test

deploy:
  image: docker:stable
  stage: deploy
  services:
    - name: docker:dind
      alias: localhost
  only:
    refs:
      - master
  script:
    - apk add bash curl git make
    - make pull
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - make push-release
    - >
      docker build --tag ssh-action ops/ssh-action/ && docker run ssh-action $BLOG_SERVER $SSH_KEY <<<EOF
        set -e
        echo "Successfully connected to `hostname`"
        exit
      EOF
